### ISSUE TITLE
Error: spawn xclip ENOENT

### ISSUE THREAD

**Issue by MaizerGomes** [marionebl/remote-share-cli#2]
OS: Linux (Elementary OS - Loki)

I was so exited to use this package, but when I run **remote-share [file]** I get the following error:
```
/home/user_name/.npm-global/lib/node_modules/remote-share-cli/cli.js:333
			throw error;
			^

Error: spawn xclip ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by tonyxu-io** [comment]
Same on CentOS 7

**Comment by marionebl** [comment]
Merged `remote-share-cli` with `share-cli`, check out `share-cli@2.0` for the fix.
